#!/bin/zsh

setup() {
  ZOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  brew update
}

install_prefs() {
  # Link and read iterm2 prefs
  ln -s "$ZOTFILES/com.googlecode.iterm2.plist" "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
  defaults read "$HOME/Library/Preferences/com.googlecode.iterm2.plist"
}

install_omz() {
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  chsh -s /bin/zsh
}

install_powerline() {
  echo "Installing powerline fonts\n"
  pushd "$HOME/workspace"
    git clone https://github.com/powerline/fonts.git powerline-fonts
    pushd powerline-fonts
      ./install.sh
    popd
  popd
}

install_luan_vim() {
  echo "Installing luan's vimfiles\n"
  pushd "$HOME"
    git clone https://github.com/luan/vimfiles.git .vim
    pushd .vim
      ./install
    popd
  popd
}

link_dotfiles() {
  ln -s "$ZOTFILES/.vimrc.local $HOME/.vimrc.local"
  ln -s "$ZOTFILES/.zshrc" "$HOME/.zshrc"
  ln -s "$ZOTFILES/tagnoster.zsh-theme" "$HOME/.oh-my-zsh/themes/tagnoster.zsh-theme"
  cp "$ZOTFILES/.gitconfig" "$HOME/.gitconfig"
  mkdir "$HOME/.hammerspoon"
  ln -s "$ZOTFILES/init.lua" "$HOME/init.lua"
}

install_neovim() {
  ln -s /usr/local/bin/nvim /usr/local/bin/vim
  source ~/.zshrc
  pip3 install neovim
}

set_defaults() {
  defaults write NSGlobalDomain KeyRepeat 1
  defaults write NSGlobalDomain InitialKeyRepeat 15
}

main() {
  setup

  brew bundle
  brew link git --force

  install_prefs
  install_powerline
  install_neovim
  install_omz
  link_dotfiles
  install_luan_vim

  set_defaults
}

main $@
