#!/bin/zsh

setup() {
  SETUPDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  brew update
}

install_omz() {
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  chsh -s /bin/zsh
}

install_powerline() {
  echo "Installing powerline fonts\n"
  pushd "$HOME/workspace"
    git clone https://github.com/powerline/fonts.git powerline-fonts
    pushd powerline-fonts
      ./install.sh
    popd
  popd
}

install_luan_vim() {
  echo "Installing luan's vimfiles\n"
  pushd "$HOME"
    git clone https://github.com/luan/vimfiles.git .vim
    pushd .vim
      ./install
    popd
  popd
}

link_dotfiles() {
  ln -s "$SETUPDIR/bin $HOME/bin"
  ln -s "$SETUPDIR/.vimrc.local $HOME/.vimrc.local"
  ln -s "$SETUPDIR/.vimrc.local.before $HOME/.vimrc.local.before"
  ln -s "$SETUPDIR/.vimrc.local.plugins $HOME/.vimrc.local.plugins"
  ln -s "$SETUPDIR/.zshrc" "$HOME/.zshrc"
  ln -s "$SETUPDIR/tagnoster.zsh-theme" "$HOME/.oh-my-zsh/themes/tagnoster.zsh-theme"
  cp "$SETUPDIR/.gitconfig" "$HOME/.gitconfig"
  mkdir "$HOME/.hammerspoon"
  ln -s "$SETUPDIR/init.lua" "$HOME/.hammerspoon/init.lua"
}

install_neovim() {
  ln -s /usr/local/bin/nvim /usr/local/bin/vim
  source ~/.zshrc
  pip3 install neovim
}

install_session_manager_plugin() {
  pushd "$HOME/Downloads"
    curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/mac/sessionmanager-bundle.zip" -o "sessionmanager-bundle.zip"
    unzip sessionmanager-bundle.zip
    sudo /usr/local/bin/python3 ./sessionmanager-bundle/install -i /usr/local/sessionmanagerplugin -b /usr/local/bin/session-manager-plugin
  popd
}

uninstall_session_manager_plugin() {
  sudo rm -rf /usr/local/sessionmanagerplugin
  sudo rm /usr/local/bin/session-manager-plugin
}

main() {
  setup

  brew bundle
  brew link git --force

  install_prefs
  install_powerline
  install_neovim
  install_omz
  link_dotfiles
  install_luan_vim
  install_session_manager_plugin
}

main $@
